In [1]:
import sqlite3
import pandas as pd

In [2]:
conn = sqlite3.connect("../data/cleaned/football_analysis.db")

In [3]:
df = pd.read_csv("../data/cleaned/football_matches_cleaned.csv")
df.head()

,match_id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,country_name,home_team_name,home_team_short_name,away_team_name,away_team_short_name,result,goal_diff,total_goals,home_points,away_points
0,1,1,1,2008/2009,1,2008-08-17,492473,9987,9993,1,...,Belgium,KRC Genk,GEN,Beerschot AC,BAC,Draw,0,2,1,1
1,2,1,1,2008/2009,1,2008-08-16,492474,10000,9994,0,...,Belgium,SV Zulte-Waregem,ZUL,Sporting Lokeren,LOK,Draw,0,0,1,1
2,3,1,1,2008/2009,1,2008-08-16,492475,9984,8635,0,...,Belgium,KSV Cercle Brugge,CEB,RSC Anderlecht,AND,Away Win,-3,3,0,3
3,4,1,1,2008/2009,1,2008-08-17,492476,9991,9998,5,...,Belgium,KAA Gent,GEN,RAEC Mons,MON,Home Win,5,5,3,0
4,5,1,1,2008/2009,1,2008-08-16,492477,7947,9985,1,...,Belgium,FCV Dender EH,DEN,Standard de Liège,STL,Away Win,-2,4,0,3

In [4]:
df.to_sql("matches", conn, if_exists="replace", index=False)

25979

In [5]:
pd.read_sql("SELECT * FROM matches LIMIT 5;", conn)

,match_id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,country_name,home_team_name,home_team_short_name,away_team_name,away_team_short_name,result,goal_diff,total_goals,home_points,away_points
0,1,1,1,2008/2009,1,2008-08-17,492473,9987,9993,1,...,Belgium,KRC Genk,GEN,Beerschot AC,BAC,Draw,0,2,1,1
1,2,1,1,2008/2009,1,2008-08-16,492474,10000,9994,0,...,Belgium,SV Zulte-Waregem,ZUL,Sporting Lokeren,LOK,Draw,0,0,1,1
2,3,1,1,2008/2009,1,2008-08-16,492475,9984,8635,0,...,Belgium,KSV Cercle Brugge,CEB,RSC Anderlecht,AND,Away Win,-3,3,0,3
3,4,1,1,2008/2009,1,2008-08-17,492476,9991,9998,5,...,Belgium,KAA Gent,GEN,RAEC Mons,MON,Home Win,5,5,3,0
4,5,1,1,2008/2009,1,2008-08-16,492477,7947,9985,1,...,Belgium,FCV Dender EH,DEN,Standard de Liège,STL,Away Win,-2,4,0,3

In [6]:
pd.read_sql("""
SELECT COUNT(*) AS total_matches
FROM matches;
""", conn)

   total_matches
0          25979

In [7]:
pd.read_sql("""
SELECT ROUND(AVG(total_goals), 2) AS avg_goals
FROM matches;
""", conn)

   avg_goals
0       2.71

In [8]:
pd.read_sql("""
SELECT result, COUNT(*) AS count
FROM matches
GROUP BY result;
""", conn)

     result  count
0  Away Win   7466
1      Draw   6596
2  Home Win  11917

In [9]:
pd.read_sql("""
SELECT 
    ROUND(100.0 * SUM(CASE WHEN result = 'Home Win' THEN 1 ELSE 0 END) / COUNT(*), 2) AS home_win_percentage
FROM matches;
""", conn)

   home_win_percentage
0                45.87

In [10]:
pd.read_sql("""
SELECT 
    league_name,
    ROUND(AVG(total_goals), 2) AS avg_goals
FROM matches
GROUP BY league_name
ORDER BY avg_goals DESC;
""", conn)

                 league_name  avg_goals
0     Netherlands Eredivisie       3.08
1   Switzerland Super League       2.93
2      Germany 1. Bundesliga       2.90
3     Belgium Jupiler League       2.80
4            Spain LIGA BBVA       2.77
5     England Premier League       2.71
6    Scotland Premier League       2.63
7              Italy Serie A       2.62
8   Portugal Liga ZON Sagres       2.53
9             France Ligue 1       2.44
10        Poland Ekstraklasa       2.42

In [11]:
pd.read_sql("""
SELECT 
    season,
    COUNT(*) AS total_matches
FROM matches
GROUP BY season
ORDER BY season;
""", conn)

      season  total_matches
0  2008/2009           3326
1  2009/2010           3230
2  2010/2011           3260
3  2011/2012           3220
4  2012/2013           3260
5  2013/2014           3032
6  2014/2015           3325
7  2015/2016           3326

In [12]:
pd.read_sql("""
SELECT 
    home_team_name,
    away_team_name,
    total_goals
FROM matches
ORDER BY total_goals DESC
LIMIT 10;
""", conn)

         home_team_name          away_team_name  total_goals
0            Motherwell               Hibernian           12
1        Real Madrid CF          Rayo Vallecano           12
2      FC Bayern Munich            Hamburger SV           11
3     Tottenham Hotspur          Wigan Athletic           10
4     Manchester United                 Arsenal           10
5               Arsenal        Newcastle United           10
6  West Bromwich Albion       Manchester United           10
7    Olympique Lyonnais  Olympique de Marseille           10
8                   PSV               Feyenoord           10
9            FC Utrecht                    Ajax           10

In [13]:
pd.read_sql("""
SELECT 
    home_team_name AS team,
    COUNT(*) AS wins
FROM matches
WHERE result = 'Home Win'
GROUP BY home_team_name
ORDER BY wins DESC
LIMIT 10;
""", conn)

                team  wins
0       FC Barcelona   131
1     Real Madrid CF   129
2             Celtic   120
3  Manchester United   116
4    Manchester City   113
5   FC Bayern Munich   109
6                PSV   105
7           Juventus   105
8           FC Basel   103
9    Atlético Madrid   103

In [14]:
pd.read_sql("""
SELECT 
    away_team_name AS team,
    COUNT(*) AS wins
FROM matches
WHERE result = 'Away Win'
GROUP BY away_team_name
ORDER BY wins DESC
LIMIT 10;
""", conn)

                team  wins
0       FC Barcelona   103
1     Real Madrid CF    99
2             Celtic    98
3           Juventus    84
4   FC Bayern Munich    84
5         SL Benfica    83
6           FC Porto    81
7               Ajax    78
8           FC Basel    77
9  Manchester United    76

In [15]:
pd.read_sql("""
SELECT 
    home_team_name AS team,
    SUM(home_team_goal) AS goals_scored
FROM matches
GROUP BY home_team_name
ORDER BY goals_scored DESC
LIMIT 10;
""", conn)

                team  goals_scored
0     Real Madrid CF           505
1       FC Barcelona           495
2             Celtic           389
3   FC Bayern Munich           382
4                PSV           370
5    Manchester City           365
6               Ajax           360
7           FC Basel           344
8  Manchester United           338
9            Chelsea           333

In [16]:
pd.read_sql("""
SELECT 
    home_team_name AS team,
    SUM(away_team_goal) AS goals_conceded
FROM matches
GROUP BY home_team_name
ORDER BY goals_conceded ASC
LIMIT 10;
""", conn)

                           team  goals_conceded
0                       Amadora              15
1                    Angers SCO              15
2                 UD Las Palmas              17
3              Uniao da Madeira              17
4              FC Ingolstadt 04              18
5                      Feirense              19
6  Termalica Bruk-Bet Nieciecza              19
7                       Watford              19
8                 Middlesbrough              20
9                      Trofense              21

In [17]:
pd.read_sql("""
SELECT 
    home_team_name AS team,
    COUNT(*) AS matches,
    SUM(CASE WHEN result = 'Home Win' THEN 1 ELSE 0 END) AS wins,
    ROUND(
        100.0 * SUM(CASE WHEN result = 'Home Win' THEN 1 ELSE 0 END) / COUNT(*), 2
    ) AS win_rate
FROM matches
GROUP BY home_team_name
HAVING matches > 50
ORDER BY win_rate DESC
LIMIT 10;
""", conn)

                team  matches  wins  win_rate
0       FC Barcelona      152   131     86.18
1     Real Madrid CF      152   129     84.87
2         SL Benfica      124   102     82.26
3           FC Porto      124   102     82.26
4   FC Bayern Munich      136   109     80.15
5             Celtic      152   120     78.95
6                PSV      136   105     77.21
7  Manchester United      152   116     76.32
8               Ajax      136   103     75.74
9     RSC Anderlecht      106    79     74.53

In [18]:
pd.read_sql("""
SELECT 
    season,
    ROUND(AVG(total_goals), 2) AS avg_goals
FROM matches
GROUP BY season
ORDER BY season;
""", conn)

      season  avg_goals
0  2008/2009       2.61
1  2009/2010       2.67
2  2010/2011       2.68
3  2011/2012       2.72
4  2012/2013       2.77
5  2013/2014       2.77
6  2014/2015       2.68
7  2015/2016       2.75

In [19]:
pd.read_sql("""
SELECT 
    ROUND(
        100.0 * SUM(CASE WHEN result = 'Draw' THEN 1 ELSE 0 END) / COUNT(*), 2
    ) AS draw_percentage
FROM matches;
""", conn)

   draw_percentage
0            25.39

In [20]:
pd.read_sql("""
SELECT 
    league_name,
    ROUND(
        100.0 * SUM(CASE WHEN result = 'Draw' THEN 1 ELSE 0 END) / COUNT(*), 2
    ) AS draw_rate
FROM matches
GROUP BY league_name
ORDER BY draw_rate DESC;
""", conn)

                 league_name  draw_rate
0             France Ligue 1      28.26
1         Poland Ekstraklasa      27.34
2              Italy Serie A      26.38
3   Portugal Liga ZON Sagres      25.97
4     England Premier League      25.76
5     Belgium Jupiler League      24.59
6    Scotland Premier League      24.51
7      Germany 1. Bundesliga      24.39
8   Switzerland Super League      24.33
9     Netherlands Eredivisie      23.73
10           Spain LIGA BBVA      23.16

# SQL Analysis Summary

Key findings from SQL analysis:

- Home teams win a higher percentage of matches, confirming home advantage
- Some leagues consistently produce more goals than others
- Top-performing teams dominate both home and away matches
- Certain teams show strong defensive performance with low goals conceded
- Match outcomes and scoring patterns vary across seasons

These insights support deeper visualization in Power BI and can guide predictive modeling.